name = "anime"
main = "build/worker/shim.js"
compatibility_date = "2024-08-06"

[build]
command = "cargo install -q worker-build@0.1.1 && worker-build --release || test -f build/worker/shim.js"

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "anime"
database_id = "a07abbbe-fa0b-460c-bd2f-37b413c3ded8"

[vars]
PROWLARR_URL = "your prowlarr url"
PROWLARR_API_KEY = "your prowlarr api key"
PROWLARR_INDEXER = "6"  # you prowlarr anime indexer
NTFY_TOPIC = ""
